#!/bin/sh
# Installs or upgrades the console in a Kubernetes cluster: the current kube
# context if one answers, else an existing k3s on this host, else a fresh
# single-node k3s. Installs Helm when it is missing. Re-running upgrades in
# place. Run with --help for the flags.
#
#   curl -sfL <raw URL>/install.sh | sh -
#   curl -sfL <raw URL>/install.sh | sh -s -- --host console.example.test
#
# update.sh is this script with MODE="update", generated by
# scripts/install/gen-scripts.sh: it only upgrades an existing release, and can
# also upgrade this host's k3s (--k3s) and node packages (--prereqs).
set -eu

MODE="install"
# Not POSIX, but every sh this runs under (dash, bash, busybox ash) has it.
# shellcheck disable=SC3040
if (set -o pipefail) 2>/dev/null; then set -o pipefail; fi

DISPLAY_NAME="Fairlead" # brand:generated displayName
SLUG="fairlead" # brand:generated slug
DEFAULT_NAMESPACE="fairlead" # brand:generated defaultNamespace
CHART_NAME="fairlead" # brand:generated chartName
IMAGE_REGISTRY="ghcr.io/dihoyt" # brand:generated imageRegistry
OWNER_LABEL="fairlead" # brand:generated ownerLabelDomain
DB_FILE="fairlead.db" # brand:generated dbFile

# A fresh k3s is the stable channel's newest release, read at install time;
# this pin is used only when the channel can't be read.
K3S_VERSION="v1.36.5+k3s1"
K3S_CHANNEL_URL="https://update.k3s.io/v1-release/channels/stable"
HELM_VERSION="v3.16.2"
HELM_SHA256_AMD64="9318379b847e333460d33d291d4c088156299a26cd93d570a7f5d0c36e50b5bb"
HELM_SHA256_ARM64="1888301aeb7d08a03b6d9f4d2b73dcd09b89c41577e80e3455c113629fc657a4"
K3S_KUBECONFIG="/etc/rancher/k3s/k3s.yaml"

NAMESPACE="$DEFAULT_NAMESPACE"
RELEASE="$SLUG"
CHART_VERSION=""
CHANNEL="edge"
IMAGE_TAG=""
CHART_REF=""
HOST=""
ORIGIN=""
INGRESS_CLASS=""
VALUES_FILES=""
KUBECONFIG_PATH=""
NO_K3S=0
YES=0
DRY_RUN=0
UNINSTALL=0
NODE_PACKAGES=1
ENABLE_DEPLOY=0
PURGE=0
TIMEOUT="5m"
NODE_PORT=""
DEFAULT_NODE_PORT=32450
UPGRADE_K3S=0
PREREQS=0
ENV_FILE=""
ENV_FILE_GIVEN=0
KEEP_ENV=0
DEFAULT_ENV_FILE="/etc/$SLUG/install.env"
RESTORE_KIT=""
RESTORE_FROM=""
RESTORE_KEY=""
NAMESPACE_GIVEN=0
RELEASE_GIVEN=0
SEED_SECRET_NAME="install-seed"
# The env-file keys the console reads (INSTALL_SEED_KEYS in
# src/contracts/onboarding.ts; a test keeps the two lists the same).
SEED_KEYS="ADMIN_PASSWORD PUBLIC_URL
CLOUDFLARE_API_TOKEN CLOUDFLARE_ACCOUNT_ID CLOUDFLARE_ZONE CLOUDFLARE_ACCESS_APPS
ENTRA_TENANT_ID ENTRA_CLIENT_ID ENTRA_CLIENT_SECRET ENTRA_ADMIN_GROUPS
STORAGE_URL STORAGE_PATH STORAGE_ENDPOINT STORAGE_USER STORAGE_SECRET
SMTP_PRESET SMTP_HOST SMTP_PORT SMTP_SECURITY SMTP_USER SMTP_PASSWORD SMTP_FROM SMTP_TO
OIDC_ISSUER OIDC_CLIENT_ID OIDC_CLIENT_SECRET OIDC_LABEL OIDC_ADMIN_GROUPS
BUNDLE BUNDLE_ACCESS BASE_DOMAIN ADMIN_EMAIL STORAGE_CLASS AUTHENTIK_BOOTSTRAP_PASSWORD"

usage() {
  if [ "$MODE" = update ]; then
    cat <<EOF
Upgrades an existing $DISPLAY_NAME install in place to the newest chart, keeping
its settings (port, host, origin, app deploys) unless a flag changes them.

Usage: update.sh [flags]

  --k3s                 Also upgrade this host's k3s to the stable channel's release
  --prereqs             Also install open-iscsi and the NFS client on this host

Flags shared with install.sh (--uninstall, --purge and --no-k3s do not apply):
EOF
  else
    cat <<EOF
Installs or upgrades $DISPLAY_NAME in a Kubernetes cluster.

Usage: install.sh [flags]
EOF
  fi
  cat <<EOF

  --namespace NS        Namespace (default: $DEFAULT_NAMESPACE)
  --release NAME        Helm release name (default: $SLUG)
  --channel NAME        Build channel: edge (default, main's builds) or next (the integration
                        branch's builds, published to a separate chart path)
  --version VERSION     Chart version (default: the newest published in the channel)
  --image-tag TAG       Image tag (default: the chart's appVersion)
  --chart REF           Chart to install: a local directory or an oci:// reference
                        (default: oci://$IMAGE_REGISTRY/charts/$CHART_NAME)
  --host HOST           Serve through an Ingress at this hostname instead of a NodePort
  --origin URL          Externally visible origin (default: http://HOST when --host is given)
  --ingress-class NAME  Ingress class (default: the cluster's default class)
  --port PORT           NodePort to serve on without --host (default: $DEFAULT_NODE_PORT)
  --values FILE         Extra Helm values file; repeatable, applied last
  --enable-deploy       Let the console deploy apps from its catalog. Creates an installer
                        ServiceAccount bound to cluster-admin; off unless given
EOF
  [ "$MODE" = update ] || cat <<EOF
  --env FILE            First install only: set the console up from this env file (admin
                        password, public URL, connectors, email, the deploy bundle; keys in
                        docs/install.md). Default: $DEFAULT_ENV_FILE when it exists.
                        Shredded once the install succeeds
  --keep-env            Keep the env file instead of shredding it
  --restore KIT         First install only: reinstall with the SECRETS_KEY sealed in this
                        recovery kit (from Backups -> This console). Asks for its passphrase,
                        or reads KIT_PASSPHRASE from the environment
  --from FILE           With --restore: a copy of the console's database (<release>-<time>.db
                        from the storage target) to start from instead of an empty one
EOF
  cat <<EOF
  --kubeconfig PATH     Use this kubeconfig instead of detecting a cluster
  --no-k3s              Never install k3s; fail if no cluster is found
  --no-node-packages    Don't install open-iscsi and the NFS client on this host's k3s node
  --timeout DURATION    How long to wait for the rollout (default: $TIMEOUT)
  --yes                 Don't ask before installing k3s or changing a cluster
  --dry-run             Print the changes instead of making them
  --uninstall           Remove the release; keeps the namespace, its Secret and the data volume
  --purge               With --uninstall, also delete the namespace and everything in it
  -h, --help            Show this help

While the registry is private, set REGISTRY_USER and REGISTRY_TOKEN (a token
with read:packages) in the environment to pull the chart and image.
EOF
}

say() { printf '%s\n' "$*"; }
warn() { printf 'warning: %s\n' "$*" >&2; }
die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}
has() { command -v "$1" >/dev/null 2>&1; }

# Mutating commands go through run so --dry-run can print them instead.
run() {
  if [ "$DRY_RUN" = 1 ]; then
    printf '+ %s\n' "$*" >&2
  else
    "$@"
  fi
}

need_arg() {
  if [ "$#" -lt 2 ] || [ -z "$2" ]; then die "$1 needs a value"; fi
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --namespace) need_arg "$@"; NAMESPACE="$2"; NAMESPACE_GIVEN=1; shift 2 ;;
    --release) need_arg "$@"; RELEASE="$2"; RELEASE_GIVEN=1; shift 2 ;;
    --channel) need_arg "$@"; CHANNEL="$2"; shift 2 ;;
    --version) need_arg "$@"; CHART_VERSION="$2"; shift 2 ;;
    --image-tag) need_arg "$@"; IMAGE_TAG="$2"; shift 2 ;;
    --chart) need_arg "$@"; CHART_REF="$2"; shift 2 ;;
    --host) need_arg "$@"; HOST="$2"; shift 2 ;;
    --origin) need_arg "$@"; ORIGIN="$2"; shift 2 ;;
    --ingress-class) need_arg "$@"; INGRESS_CLASS="$2"; shift 2 ;;
    --port) need_arg "$@"; NODE_PORT="$2"; shift 2 ;;
    --values)
      need_arg "$@"
      [ -r "$2" ] || die "cannot read values file $2"
      VALUES_FILES="$VALUES_FILES$2
"
      shift 2
      ;;
    --kubeconfig) need_arg "$@"; KUBECONFIG_PATH="$2"; shift 2 ;;
    --timeout) need_arg "$@"; TIMEOUT="$2"; shift 2 ;;
    --enable-deploy) ENABLE_DEPLOY=1; shift ;;
    --env) need_arg "$@"; ENV_FILE="$2"; ENV_FILE_GIVEN=1; shift 2 ;;
    --keep-env) KEEP_ENV=1; shift ;;
    --restore) need_arg "$@"; RESTORE_KIT="$2"; shift 2 ;;
    --from) need_arg "$@"; RESTORE_FROM="$2"; shift 2 ;;
    --no-k3s) NO_K3S=1; shift ;;
    --no-node-packages) NODE_PACKAGES=0; shift ;;
    --k3s) UPGRADE_K3S=1; shift ;;
    --prereqs) PREREQS=1; shift ;;
    --yes | -y) YES=1; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    --uninstall) UNINSTALL=1; shift ;;
    --purge) PURGE=1; shift ;;
    -h | --help) usage; exit 0 ;;
    *) die "unknown flag $1 (see --help)" ;;
  esac
done

# Everything below lands in YAML or a resource name, so only plain characters.
dns_label() {
  case "$2" in
    "" | -* | *- | *[!a-z0-9-]*) die "$1 must be a lowercase DNS label: $2" ;;
  esac
}
dns_label --namespace "$NAMESPACE"
dns_label --release "$RELEASE"
case "$HOST" in *[!A-Za-z0-9.-]*) die "--host must be a hostname: $HOST" ;; esac
case "$ORIGIN" in
  "") ;;
  *[!A-Za-z0-9.:/_-]*) die "--origin must be a plain URL: $ORIGIN" ;;
  http://* | https://*) ;;
  *) die "--origin must start with http:// or https://" ;;
esac
case "$CHANNEL" in edge | next) ;; *) die "--channel must be edge or next: $CHANNEL" ;; esac
case "$IMAGE_TAG" in *[!A-Za-z0-9._-]*) die "--image-tag has unexpected characters: $IMAGE_TAG" ;; esac
case "$INGRESS_CLASS" in *[!a-z0-9.-]*) die "--ingress-class has unexpected characters" ;; esac
case "$NODE_PORT" in
  "") ;;
  *[!0-9]*) die "--port must be a number: $NODE_PORT" ;;
  *) if [ "$NODE_PORT" -lt 30000 ] || [ "$NODE_PORT" -gt 32767 ]; then die "--port must be in the NodePort range 30000-32767"; fi ;;
esac
[ -z "$NODE_PORT" ] || [ -z "$HOST" ] || die "--port is for the NodePort install; --host serves through an Ingress"
[ "$PURGE" = 0 ] || [ "$UNINSTALL" = 1 ] || die "--purge only goes with --uninstall"
if [ "$MODE" = update ]; then
  [ "$UNINSTALL" = 0 ] || die "update.sh does not uninstall; use install.sh --uninstall"
  if [ "$ENV_FILE_GIVEN" = 1 ] || [ "$KEEP_ENV" = 1 ]; then die "--env and --keep-env set up a first install; use install.sh"; fi
  NO_K3S=1
else
  if [ "$UPGRADE_K3S" = 1 ] || [ "$PREREQS" = 1 ]; then die "--k3s and --prereqs are update.sh flags"; fi
  if [ "$UNINSTALL" = 1 ] && { [ "$ENV_FILE_GIVEN" = 1 ] || [ "$KEEP_ENV" = 1 ]; }; then die "--env does not go with --uninstall"; fi
  if [ "$ENV_FILE_GIVEN" = 0 ] && [ "$UNINSTALL" = 0 ] && [ -e "$DEFAULT_ENV_FILE" ]; then ENV_FILE="$DEFAULT_ENV_FILE"; fi
  [ "$KEEP_ENV" = 0 ] || [ -n "$ENV_FILE" ] || die "--keep-env goes with --env"
fi
[ "$ENABLE_DEPLOY" = 0 ] || [ "$UNINSTALL" = 0 ] || die "--enable-deploy does not go with --uninstall"
if [ -n "$RESTORE_KIT" ] || [ -n "$RESTORE_FROM" ]; then
  [ "$MODE" = install ] || die "--restore and --from reinstall from a backup; use install.sh"
  [ "$UNINSTALL" = 0 ] || die "--restore does not go with --uninstall"
  [ -z "$ENV_FILE" ] || die "--restore and --env both set up a first install; use one (move $ENV_FILE away)"
  [ -n "$RESTORE_KIT" ] || die "--from goes with --restore: without the kit's key the copy's stored secrets can't be read"
  if [ -n "$RESTORE_FROM" ]; then
    [ -r "$RESTORE_FROM" ] || die "cannot read database copy $RESTORE_FROM"
    [ "$(head -c 15 "$RESTORE_FROM")" = "SQLite format 3" ] || die "$RESTORE_FROM is not a SQLite database"
  fi
fi
[ -n "$ORIGIN" ] || [ -z "$HOST" ] || ORIGIN="http://$HOST"
if [ -z "$CHART_REF" ]; then
  if [ "$CHANNEL" = next ]; then CHART_REF="oci://$IMAGE_REGISTRY/charts-next/$CHART_NAME"; else CHART_REF="oci://$IMAGE_REGISTRY/charts/$CHART_NAME"; fi
fi

SECRET_NAME="$RELEASE-secrets"
PULL_SECRET_NAME="$RELEASE-registry"

if [ "$(id -u)" = 0 ]; then
  SUDO=""
else
  SUDO="sudo"
fi
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT INT TERM

tty_ok() { (exec </dev/tty) 2>/dev/null; }

# Checks the env file before anything is changed and writes its values,
# unquoted, to $TMP/seed.env. Errors name the line and the key, never a
# value: the file holds passwords and tokens.
SEED_COUNT=0
SEED_ADMIN_PASSWORD=0
read_env_file() {
  reader=""
  if [ ! -r "$ENV_FILE" ]; then
    { [ -e "$ENV_FILE" ] && [ -n "$SUDO" ]; } || die "cannot read env file $ENV_FILE"
    reader="$SUDO"
  fi
  # shellcheck disable=SC2086
  case "$($reader ls -ln "$ENV_FILE" | cut -c5-10)" in
    *[rwx]*) warn "other users on this host can read $ENV_FILE (chmod 600 it)" ;;
  esac
  (
    umask 077
    # shellcheck disable=SC2086
    $reader cat "$ENV_FILE" >"$TMP/env.raw"
    : >"$TMP/seed.env"
  ) || die "cannot read env file $ENV_FILE"
  keys=" $(printf '%s' "$SEED_KEYS" | tr '\n' ' ') "
  bundle=0
  n=0
  seen=" "
  while IFS= read -r line || [ -n "$line" ]; do
    n=$((n + 1))
    line=$(printf '%s' "$line" | sed 's/\r$//; s/^[[:space:]]*//; s/^export[[:space:]][[:space:]]*//')
    case "$line" in "" | "#"*) continue ;; esac
    key=${line%%=*}
    case "$line" in *=*) ;; *) key="" ;; esac
    case "$key" in "" | [!A-Z]* | *[!A-Z0-9_]*) die "line $n of $ENV_FILE is not KEY=value" ;; esac
    case "$keys" in *" $key "*) ;; *) die "unknown key $key on line $n of $ENV_FILE (docs/install.md lists the keys)" ;; esac
    case "$seen" in *" $key "*) die "$key is set twice in $ENV_FILE (line $n)" ;; esac
    seen="$seen$key "
    value=${line#*=}
    case "$value" in
      \"*\") value=${value#\"}; value=${value%\"} ;;
      \'*\') value=${value#\'}; value=${value%\'} ;;
    esac
    [ -n "$value" ] || continue
    printf '%s=%s\n' "$key" "$value" >>"$TMP/seed.env"
    SEED_COUNT=$((SEED_COUNT + 1))
    case "$key" in
      ADMIN_PASSWORD)
        [ "${#value}" -ge 10 ] || die "ADMIN_PASSWORD in $ENV_FILE is shorter than 10 characters"
        SEED_ADMIN_PASSWORD=1
        ;;
      BUNDLE) bundle=1 ;;
    esac
  done <"$TMP/env.raw"
  rm -f "$TMP/env.raw"
  [ "$SEED_COUNT" -gt 0 ] || die "$ENV_FILE sets none of the keys docs/install.md lists"
  if [ "$bundle" = 1 ] && [ "$ENABLE_DEPLOY" = 0 ]; then
    warn "BUNDLE needs --enable-deploy; without it the console reports the bundle as failed"
  fi
}

# The Secret the console reads once at first boot and then deletes. Values
# reach kubectl base64 in a 0600 file, never as an argument.
write_seed_secret() {
  (
    umask 077
    {
      say "apiVersion: v1"
      say "kind: Secret"
      say "metadata:"
      say "  name: $SEED_SECRET_NAME"
      say "  namespace: $NAMESPACE"
      say "  labels:"
      say "    app.kubernetes.io/managed-by: $OWNER_LABEL"
      say "type: Opaque"
      say "data:"
      while IFS= read -r line; do
        printf '  %s: %s\n' "${line%%=*}" "$(printf '%s' "${line#*=}" | base64 | tr -d '\n')"
      done <"$TMP/seed.env"
    } >"$TMP/seed-secret.yaml"
  )
  run kube apply -f "$TMP/seed-secret.yaml" >/dev/null
  rm -f "$TMP/seed-secret.yaml" "$TMP/seed.env"
  say "Stored $SEED_COUNT settings from $ENV_FILE in Secret $SEED_SECRET_NAME; the console applies them at first boot."
}

# shred overwrites the file in place; without it, zeros its own size do.
remove_env_file() {
  if [ "$KEEP_ENV" = 1 ]; then
    say "Kept $ENV_FILE (--keep-env). It holds passwords and tokens: delete it when you are done."
    return 0
  fi
  if [ -w "$ENV_FILE" ] && [ -w "$(dirname "$ENV_FILE")" ]; then as=""; else as="$SUDO"; fi
  # shellcheck disable=SC2086
  if has shred; then
    run $as shred -u "$ENV_FILE"
  else
    size=$($as wc -c <"$ENV_FILE" | tr -d ' ')
    run $as dd if=/dev/zero of="$ENV_FILE" bs=1 count="$size" conv=notrunc 2>/dev/null \
      && run $as rm -f "$ENV_FILE"
  fi || {
    warn "could not delete $ENV_FILE; it holds passwords and tokens, so delete it yourself"
    return 0
  }
  say "Shredded $ENV_FILE (--keep-env keeps it)."
}

confirm() {
  [ "$YES" = 1 ] && return 0
  if tty_ok; then
    printf '%s [y/N] ' "$1" >/dev/tty
    read -r answer </dev/tty || answer=""
    case "$answer" in y | Y | yes | YES) return 0 ;; esac
    die "cancelled"
  fi
  die "$1 No terminal to ask on: re-run with --yes."
}

# kubectl and helm against the chosen cluster. KSUDO is set when the only
# kubeconfig is k3s's root-only one.
KSUDO=""
KUBECTL="kubectl"
kube() {
  if [ -n "$KUBECONFIG_PATH" ]; then
    # shellcheck disable=SC2086
    $KSUDO $KUBECTL --kubeconfig "$KUBECONFIG_PATH" "$@"
  else
    # shellcheck disable=SC2086
    $KUBECTL "$@"
  fi
}
hh() {
  if [ -n "$KUBECONFIG_PATH" ]; then
    $KSUDO helm --kubeconfig "$KUBECONFIG_PATH" "$@"
  else
    helm "$@"
  fi
}

pick_kubectl() {
  if has kubectl; then
    KUBECTL="kubectl"
  elif has k3s; then
    KUBECTL="k3s kubectl"
  else
    die "kubectl is not installed"
  fi
}

reachable() { kube get --raw /readyz --request-timeout=10s >/dev/null 2>&1; }

# Why reachable failed: an API server that answers /livez but not /readyz is
# up with a failing check (often the datastore on a host short of memory).
# kubectl puts a 500's body on one line with the newlines escaped.
unreachable_detail() {
  kube get --raw /livez --request-timeout=10s >/dev/null 2>&1 || return 0
  failing=$(kube get --raw '/readyz?verbose' --request-timeout=10s 2>&1 | sed 's/\\n/\
/g' | grep '^\[-\]' | sed 's/^/  /' || true)
  printf 'its API server is not ready. Failing checks:\n%s\n' "${failing:-  (none listed; see $(kubectl_hint) get --raw '/readyz?verbose')}"
}

use_k3s_kubeconfig() {
  KUBECONFIG_PATH="$K3S_KUBECONFIG"
  if [ -r "$KUBECONFIG_PATH" ]; then KSUDO=""; else KSUDO="$SUDO"; fi
  pick_kubectl
}

# The channel answers with a redirect to its newest release's tag page.
resolve_k3s_version() {
  tag=$(curl -sS -o /dev/null -w '%{redirect_url}' --max-time 15 "$K3S_CHANNEL_URL" 2>/dev/null || true)
  tag=$(printf '%s' "${tag##*/}" | sed 's/%2[Bb]/+/g')
  case "$tag" in
    *[!A-Za-z0-9.+]*) ;;
    v1.[0-9]*+k3s[0-9]*)
      K3S_VERSION="$tag"
      return 0
      ;;
  esac
  warn "could not read the k3s stable channel; installing the pinned $K3S_VERSION"
}

install_k3s() {
  [ "$NO_K3S" = 0 ] || die "no cluster found and --no-k3s was given"
  [ "$(uname -s)" = Linux ] || die "no cluster found, and k3s can only be installed on Linux"
  has curl || die "curl is required"
  resolve_k3s_version
  confirm "No cluster found. Install k3s $K3S_VERSION (single node) on this host?"
  say "Installing k3s $K3S_VERSION ..."
  # The installer from the same tag as the binary, which it checksums.
  curl -sfL "https://raw.githubusercontent.com/k3s-io/k3s/$K3S_VERSION/install.sh" -o "$TMP/k3s-install.sh" \
    || die "could not download the k3s installer"
  run env INSTALL_K3S_VERSION="$K3S_VERSION" sh "$TMP/k3s-install.sh"
  [ "$DRY_RUN" = 0 ] || return 0
  use_k3s_kubeconfig
  i=0
  until [ -n "$(kube get nodes -o name 2>/dev/null)" ]; do
    i=$((i + 1))
    [ "$i" -le 60 ] || die "k3s started but no node registered"
    sleep 2
  done
  kube wait --for=condition=Ready node --all --timeout=180s >/dev/null
}

# Longhorn needs iscsid on every node, and an NFS client for its backups and
# ReadWriteMany volumes. Only this host is reachable from here, and only when
# it is the k3s node; other nodes are a documented manual step.
node_packages() {
  [ "$NODE_PACKAGES" = 1 ] || return 0
  if has iscsiadm && { has mount.nfs || [ -x /sbin/mount.nfs ] || [ -x /usr/sbin/mount.nfs ]; }; then
    start_iscsid
    return 0
  fi
  if has apt-get; then
    set -- open-iscsi nfs-common
  elif has dnf; then
    set -- iscsi-initiator-utils nfs-utils
  elif has yum; then
    set -- iscsi-initiator-utils nfs-utils
  elif has zypper; then
    set -- open-iscsi nfs-client
  elif has apk; then
    set -- open-iscsi nfs-utils
  else
    say "Longhorn needs open-iscsi and an NFS client on each node; no known package manager here, so install them yourself."
    return 0
  fi
  if [ "$YES" = 0 ] && tty_ok; then
    printf 'Install %s on this host (Longhorn needs them)? [Y/n] ' "$*" >/dev/tty
    read -r answer </dev/tty || answer=""
    case "$answer" in n | N | no | NO) say "Skipped $*; Longhorn will not start on this node without them."; return 0 ;; esac
  fi
  say "Installing $* ..."
  # shellcheck disable=SC2086
  if has apt-get; then
    run $SUDO env DEBIAN_FRONTEND=noninteractive apt-get update -qq >/dev/null &&
      run $SUDO env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq "$@" >/dev/null
  elif has dnf; then
    run $SUDO dnf install -y -q "$@" >/dev/null
  elif has yum; then
    run $SUDO yum install -y -q "$@" >/dev/null
  elif has zypper; then
    run $SUDO zypper --non-interactive --quiet install "$@" >/dev/null
  else
    run $SUDO apk add --quiet "$@" >/dev/null
  fi || {
    warn "could not install $*; Longhorn will not start on this node until they are installed"
    return 0
  }
  start_iscsid
}

start_iscsid() {
  # shellcheck disable=SC2086
  if has systemctl; then
    run $SUDO systemctl enable --now iscsid >/dev/null 2>&1
  elif has rc-update; then
    run $SUDO rc-update add iscsid >/dev/null 2>&1 && run $SUDO rc-service iscsid start >/dev/null 2>&1
  fi || warn "could not start iscsid; Longhorn needs it running"
}

# A binary swap and a service restart, as k3s documents for manual upgrades:
# re-running k3s's installer would rewrite the service from this run's flags
# and lose the ones it was installed with (an agent's server URL, for one).
upgrade_k3s() {
  if [ "$KUBECONFIG_PATH" != "$K3S_KUBECONFIG" ] || ! has k3s; then
    die "--k3s upgrades this host's k3s, and the cluster in use is not it"
  fi
  current=$(k3s --version 2>/dev/null | sed -n 's/^k3s version \([^ ]*\).*/\1/p')
  resolve_k3s_version
  if [ "$current" = "$K3S_VERSION" ]; then
    say "k3s is already $current."
    return 0
  fi
  if [ "$(printf '%s\n%s\n' "$current" "$K3S_VERSION" | sort -V | tail -n 1)" = "$current" ]; then
    say "k3s $current is newer than $K3S_VERSION; leaving it."
    return 0
  fi
  case "$(uname -m)" in
    x86_64 | amd64) bin=k3s; sums=sha256sum-amd64.txt ;;
    aarch64 | arm64) bin=k3s-arm64; sums=sha256sum-arm64.txt ;;
    *) die "no k3s build for $(uname -m)" ;;
  esac
  if systemctl is-active --quiet k3s 2>/dev/null; then
    unit=k3s
  elif systemctl is-active --quiet k3s-agent 2>/dev/null; then
    unit=k3s-agent
  else
    die "no running k3s or k3s-agent service to restart"
  fi
  confirm "Upgrade this host's k3s from $current to $K3S_VERSION? Other nodes are not upgraded."
  base="https://github.com/k3s-io/k3s/releases/download/$(printf '%s' "$K3S_VERSION" | sed 's/+/%2B/')"
  curl -sfL "$base/$sums" -o "$TMP/$sums" || die "could not download the k3s checksums"
  curl -sfL "$base/$bin" -o "$TMP/k3s" || die "could not download k3s $K3S_VERSION"
  expected=$(awk -v f="$bin" '$2 == f { print $1 }' "$TMP/$sums")
  if has sha256sum; then
    actual=$(sha256sum "$TMP/k3s" | cut -d' ' -f1)
  else
    actual=$(shasum -a 256 "$TMP/k3s" | cut -d' ' -f1)
  fi
  if [ -z "$expected" ] || [ "$actual" != "$expected" ]; then
    die "k3s checksum mismatch: expected $expected, got $actual"
  fi
  say "Upgrading k3s to $K3S_VERSION ..."
  # shellcheck disable=SC2086
  run $SUDO install -m 0755 "$TMP/k3s" "$(command -v k3s)"
  # shellcheck disable=SC2086
  run $SUDO systemctl restart "$unit"
  [ "$DRY_RUN" = 0 ] || return 0
  i=0
  until reachable; do
    i=$((i + 1))
    [ "$i" -le 60 ] || die "k3s did not come back after the upgrade (systemctl status $unit)"
    sleep 2
  done
  kube wait --for=condition=Ready node --all --timeout=180s >/dev/null
}

release_chart() { hh list -n "$NAMESPACE" --filter "^$RELEASE\$" 2>/dev/null | awk 'NR == 2 { print $(NF - 1) }'; }
release_image() { kube -n "$NAMESPACE" get deploy "$RELEASE" -o jsonpath='{.spec.template.spec.containers[0].image}' 2>/dev/null || true; }

use_host_k3s() {
  use_k3s_kubeconfig
  if ! reachable; then
    detail=$(unreachable_detail)
    die "k3s is installed, but ${detail:-its API server does not answer} (systemctl status k3s, journalctl -u k3s -n 50, free -m)"
  fi
  say "Using this host's k3s."
}

find_cluster() {
  if [ -n "$KUBECONFIG_PATH" ]; then
    [ -r "$KUBECONFIG_PATH" ] || die "cannot read $KUBECONFIG_PATH"
    pick_kubectl
    if ! reachable; then
      detail=$(unreachable_detail)
      die "the cluster in $KUBECONFIG_PATH ${detail:+answers, but }${detail:-does not answer}"
    fi
    say "Using the cluster in $KUBECONFIG_PATH."
    return 0
  fi
  # k3s's kubectl symlink falls back to k3s.yaml when nothing else is
  # configured, but helm does not, so with no kubeconfig of the caller's own
  # this host's k3s is used explicitly for both.
  if [ -z "${KUBECONFIG:-}" ] && [ ! -f "${HOME:-/nonexistent}/.kube/config" ] && [ -f "$K3S_KUBECONFIG" ]; then
    use_host_k3s
    return 0
  fi
  if has kubectl && reachable; then
    say "Using kube context $(kube config current-context 2>/dev/null || echo '(unnamed)')."
    if [ "$MODE" = update ]; then
      confirm "Update $RELEASE in this cluster?"
    elif [ "$UNINSTALL" = 0 ]; then
      confirm "Install into this cluster?"
    fi
    return 0
  fi
  if [ -f "$K3S_KUBECONFIG" ]; then
    use_host_k3s
    return 0
  fi
  if [ "$UNINSTALL" = 1 ] || [ "$MODE" = update ]; then die "no cluster found"; fi
  install_k3s
}

helm_ok() {
  has helm || return 1
  # OCI charts need Helm 3.8+.
  v=$(helm version --template '{{.Version}}' 2>/dev/null || echo v0)
  case "$v" in
    v3.[0-7].* | v[0-2].*) warn "helm $v is too old for OCI charts"; return 1 ;;
  esac
}

install_helm() {
  helm_ok && return 0
  has curl || die "curl is required"
  case "$(uname -m)" in
    x86_64 | amd64) arch=amd64; sum="$HELM_SHA256_AMD64" ;;
    aarch64 | arm64) arch=arm64; sum="$HELM_SHA256_ARM64" ;;
    *) die "no pinned Helm build for $(uname -m); install Helm 3.8+ and re-run" ;;
  esac
  say "Installing Helm $HELM_VERSION ..."
  tarball="helm-$HELM_VERSION-linux-$arch.tar.gz"
  curl -sfL "https://get.helm.sh/$tarball" -o "$TMP/$tarball" || die "could not download Helm"
  if has sha256sum; then
    actual=$(sha256sum "$TMP/$tarball" | cut -d' ' -f1)
  else
    actual=$(shasum -a 256 "$TMP/$tarball" | cut -d' ' -f1)
  fi
  [ "$actual" = "$sum" ] || die "Helm checksum mismatch: expected $sum, got $actual"
  tar -xzf "$TMP/$tarball" -C "$TMP"
  # shellcheck disable=SC2086
  run $SUDO install -m 0755 "$TMP/linux-$arch/helm" /usr/local/bin/helm
}

random_hex() { head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'; }

# What this script and the chart create, plus the Pods those make. A webhook
# whose rules name none of these can't fail the install, so it only warns.
WEBHOOK_KINDS=" * */* namespaces secrets configmaps services serviceaccounts pods persistentvolumeclaims deployments replicasets jobs roles rolebindings clusterroles clusterrolebindings ingresses "

# A Fail-policy admission webhook whose Service has no ready endpoint (left
# behind when Rancher's agent, an operator or a policy engine is removed
# without its webhook configuration) makes the API server refuse every
# matching write. Found here, before anything is written, rather than as a
# raw error half-way through. Nothing is deleted: the fix is printed.
check_webhooks() {
  # shellcheck disable=SC2016
  tpl='{{range .items}}{{$c := .metadata.name}}{{range .webhooks}}{{if .clientConfig.service}}{{$c}} {{.name}} {{.clientConfig.service.namespace}} {{.clientConfig.service.name}} {{.failurePolicy}} {{range .rules}}{{range .resources}}{{.}},{{end}}{{end}}{{"\n"}}{{end}}{{end}}{{end}}'
  blocking=""
  stale=""
  for kind in validatingwebhookconfigurations mutatingwebhookconfigurations; do
    hooks=$(kube get "$kind" -o go-template="$tpl" 2>/dev/null) || continue
    while read -r config hook svc_ns svc policy resources; do
      if [ -z "$config" ] || [ "$policy" = Ignore ]; then continue; fi
      ready=$(kube -n "$svc_ns" get endpointslices -l "kubernetes.io/service-name=$svc" \
        -o go-template='{{range .items}}{{range .endpoints}}{{if .conditions.ready}}y{{end}}{{end}}{{end}}' 2>/dev/null || true)
      [ -z "$ready" ] || continue
      line="  ${kind%s}/$config: webhook $hook -> service $svc_ns/$svc"
      matches=0
      old_ifs="$IFS"
      IFS=,
      set -f
      for r in $resources; do
        case "$WEBHOOK_KINDS" in *" $r "*) matches=1 ;; esac
      done
      set +f
      IFS="$old_ifs"
      if [ "$matches" = 1 ]; then
        blocking="$blocking$line
"
        case " $stale " in *" ${kind%s}/$config "*) ;; *) stale="$stale ${kind%s}/$config" ;; esac
      else
        warn "admission webhook $hook ($svc_ns/$svc) has no running pods; writes it covers will fail"
      fi
    done <<EOF
$hooks
EOF
  done
  [ -n "$blocking" ] || return 0
  printf 'error: these admission webhooks point at a service with no running pods, so the cluster refuses the objects this script writes:\n%s' "$blocking" >&2
  printf 'If what served them is gone (a Rancher agent or operator that was removed), delete them and run this again:\n' >&2
  printf '  %s delete%s\n' "$(kubectl_hint)" "$stale" >&2
  printf 'If it should still be running, get its pods running first, then run this again.\n' >&2
  exit 1
}

ensure_namespace() {
  kube get namespace "$NAMESPACE" >/dev/null 2>&1 || run kube create namespace "$NAMESPACE" >/dev/null
}

K3S_TOKEN_DIR="/var/lib/rancher/k3s/server"
JOIN_SECRET_NAME="k3s-join"

# What a new node needs to join, for the console's join links. Written on
# every run from this host's k3s server, so a rotated token or a new address
# follows. The token goes from root's file to a 0600 temp file to kubectl,
# never through an argument or the output.
ensure_join_secret() {
  # shellcheck disable=SC2086
  if [ "$KUBECONFIG_PATH" != "$K3S_KUBECONFIG" ] || ! $SUDO test -r "$K3S_TOKEN_DIR/node-token" 2>/dev/null; then
    say "Not on a k3s server node, so adding nodes from the console stays off (run this on the server to turn it on)."
    return 0
  fi
  ip=$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{ for (i = 1; i < NF; i++) if ($i == "src") { print $(i + 1); exit } }')
  [ -n "$ip" ] || ip=$(node_ip)
  [ -n "$ip" ] || { warn "could not find this host's IP; adding nodes from the console stays off"; return 0; }
  (
    umask 077
    printf 'https://%s:6443' "$ip" >"$TMP/server-url"
    $SUDO cat "$K3S_TOKEN_DIR/node-token" | tr -d '\n' >"$TMP/token"
    if $SUDO test -s "$K3S_TOKEN_DIR/agent-token" 2>/dev/null; then
      $SUDO cat "$K3S_TOKEN_DIR/agent-token" | tr -d '\n' >"$TMP/agent-token"
    fi
  )
  set -- --from-file=server-url="$TMP/server-url" --from-file=token="$TMP/token"
  [ ! -s "$TMP/agent-token" ] || set -- "$@" --from-file=agent-token="$TMP/agent-token"
  kube -n "$NAMESPACE" create secret generic "$JOIN_SECRET_NAME" "$@" --dry-run=client -o yaml >"$TMP/join-secret.yaml"
  rm -f "$TMP/server-url" "$TMP/token" "$TMP/agent-token"
  run kube -n "$NAMESPACE" apply -f "$TMP/join-secret.yaml" >/dev/null
  run kube -n "$NAMESPACE" label --overwrite secret "$JOIN_SECRET_NAME" "app.kubernetes.io/managed-by=$OWNER_LABEL" >/dev/null
  rm -f "$TMP/join-secret.yaml"
}

# Created once. A re-run never replaces it: the data volume is sealed with
# SECRETS_KEY, and the bootstrap password only matters before first sign-in.
PASSWORD=""
ensure_secret() {
  if kube -n "$NAMESPACE" get secret "$SECRET_NAME" >/dev/null 2>&1; then
    return 0
  fi
  PASSWORD=$(head -c 18 /dev/urandom | base64 | tr '+/' 'xy')
  (
    umask 077
    printf 'SECRETS_KEY=%s\nBOOTSTRAP_ADMIN_PASSWORD=%s\n' "$(random_hex 32)" "$PASSWORD" >"$TMP/secret.env"
  )
  run kube -n "$NAMESPACE" create secret generic "$SECRET_NAME" --from-env-file="$TMP/secret.env" >/dev/null
  run kube -n "$NAMESPACE" label secret "$SECRET_NAME" "app.kubernetes.io/managed-by=$OWNER_LABEL" >/dev/null
  rm -f "$TMP/secret.env"
}

# Only while the registry is private: log Helm in for the chart and give the
# pod a pull secret for the image.
PULL_SECRET=0
registry_auth() {
  if [ -z "${REGISTRY_USER:-}" ] || [ -z "${REGISTRY_TOKEN:-}" ]; then return 0; fi
  registry_host="${IMAGE_REGISTRY%%/*}"
  case "$CHART_REF" in
    oci://*)
      if [ "$DRY_RUN" = 0 ]; then
        printf '%s' "$REGISTRY_TOKEN" | hh registry login "$registry_host" --username "$REGISTRY_USER" --password-stdin >/dev/null
      fi
      ;;
  esac
  auth=$(printf '%s:%s' "$REGISTRY_USER" "$REGISTRY_TOKEN" | base64 | tr -d '\n')
  (
    umask 077
    printf '{"auths":{"%s":{"auth":"%s"}}}\n' "$registry_host" "$auth" >"$TMP/dockerconfig.json"
  )
  kube -n "$NAMESPACE" create secret generic "$PULL_SECRET_NAME" --type=kubernetes.io/dockerconfigjson \
    --from-file=.dockerconfigjson="$TMP/dockerconfig.json" --dry-run=client -o yaml >"$TMP/pull-secret.yaml"
  run kube -n "$NAMESPACE" apply -f "$TMP/pull-secret.yaml" >/dev/null
  rm -f "$TMP/dockerconfig.json" "$TMP/pull-secret.yaml"
  PULL_SECRET=1
}

default_ingress_class() {
  [ -z "$INGRESS_CLASS" ] || return 0
  default=$(kube get ingressclass -o jsonpath='{range .items[?(@.metadata.annotations.ingressclass\.kubernetes\.io/is-default-class=="true")]}{.metadata.name}{"\n"}{end}' 2>/dev/null || true)
  [ -z "$default" ] || return 0
  # k3s's Traefik class is not marked default; one class is unambiguous.
  classes=$(kube get ingressclass -o name 2>/dev/null || true)
  case "$classes" in
    "") warn "no IngressClass in this cluster: the Ingress will need a controller to serve it" ;;
    *"
"*) warn "several IngressClasses and none is the default: pass --ingress-class" ;;
    *) INGRESS_CLASS="${classes#*/}" ;;
  esac
}

# Settings this run decides. On a first install they are the defaults; on an
# upgrade only what was asked for, on top of the release's previous values.
write_values() {
  first="$1"
  f="$TMP/values.yaml"
  {
    say "secrets:"
    say "  existingSecret: \"$SECRET_NAME\""
    [ -z "$IMAGE_TAG" ] || printf 'image:\n  tag: "%s"\n' "$IMAGE_TAG"
    [ "$PULL_SECRET" = 0 ] || printf 'imagePullSecrets:\n  - "%s"\n' "$PULL_SECRET_NAME"
    # Only ever turned on here; a re-run without the flag keeps what the release has.
    [ "$ENABLE_DEPLOY" = 0 ] || printf 'deploy:\n  enabled: true\n'
    if [ -n "$HOST" ]; then
      printf 'config:\n  publicOrigin: "%s"\n' "$ORIGIN"
      say "service:"
      say "  type: ClusterIP"
      say "ingress:"
      say "  enabled: true"
      [ -z "$INGRESS_CLASS" ] || say "  className: \"$INGRESS_CLASS\""
      say "  hosts:"
      say "    - host: \"$HOST\""
    else
      [ -z "$ORIGIN" ] || printf 'config:\n  publicOrigin: "%s"\n' "$ORIGIN"
      if [ "$first" = 1 ] || [ -n "$NODE_PORT" ]; then
        say "service:"
        say "  type: NodePort"
        [ -z "$NODE_PORT" ] || say "  nodePort: $NODE_PORT"
      fi
    fi
  } >"$f"
}

# A taken port fails the install here, with its owner named, rather than
# in Helm's error or by falling back to a random port. On a re-run without
# --port the port is the one the release asked for before, else the default.
check_node_port() {
  want="$NODE_PORT"
  if [ -z "$want" ] && [ "$1" = 1 ]; then
    [ "$(kube -n "$NAMESPACE" get svc "$RELEASE" -o jsonpath='{.spec.type}' 2>/dev/null || true)" = NodePort ] || return 0
    want=$(hh get values "$RELEASE" -n "$NAMESPACE" -o yaml 2>/dev/null | sed -n 's/^  nodePort: *"*\([0-9]*\)"*$/\1/p' | head -n 1)
  fi
  want="${want:-$DEFAULT_NODE_PORT}"
  owner=$(kube get svc -A -o jsonpath='{range .items[*]}{.metadata.namespace}/{.metadata.name} {.spec.ports[*].nodePort}{"\n"}{end}' 2>/dev/null \
    | awk -v port="$want" -v self="$NAMESPACE/$RELEASE" '$1 != self { for (i = 2; i <= NF; i++) if ($i == port) print $1 }' | head -n 1)
  [ -z "$owner" ] || die "NodePort $want is already used by Service $owner; pick another with --port (30000-32767)"
}

node_ip() {
  ips=$(kube get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')
  printf '%s' "${ips%% *}"
}

# How someone reads the password later, in the form that works on this host.
kubectl_hint() {
  if [ -n "$KUBECONFIG_PATH" ] && [ "$KUBECONFIG_PATH" = "$K3S_KUBECONFIG" ]; then
    if [ -n "$KSUDO" ]; then printf 'sudo k3s kubectl'; else printf 'k3s kubectl'; fi
  elif [ -n "$KUBECONFIG_PATH" ]; then
    printf 'kubectl --kubeconfig %s' "$KUBECONFIG_PATH"
  else
    printf 'kubectl'
  fi
}

do_uninstall() {
  find_cluster
  helm_ok || die "helm is not installed"
  if hh status "$RELEASE" -n "$NAMESPACE" >/dev/null 2>&1; then
    confirm "Remove release $RELEASE from namespace $NAMESPACE?"
    run hh uninstall "$RELEASE" -n "$NAMESPACE" --wait
  else
    say "No release $RELEASE in namespace $NAMESPACE."
  fi
  if [ "$PURGE" = 1 ]; then
    if kube get namespace "$NAMESPACE" >/dev/null 2>&1; then
      confirm "Delete namespace $NAMESPACE, including its data volume and Secret?"
      run kube delete namespace "$NAMESPACE" --wait=true
    fi
    say "Removed."
  else
    say "Removed the release. Kept namespace $NAMESPACE with its Secret $SECRET_NAME and data volume,"
    say "so a later install picks up where this one left off. --uninstall --purge deletes them."
  fi
}

# --- Restore from a recovery kit and a database copy ------------------------

# The kit is "#" comment lines and one base64 line that openssl opens with
# the passphrase (src/platform/recoveryKit.ts). Its RELEASE and NAMESPACE
# stand in for flags not given.
open_kit() {
  [ -r "$RESTORE_KIT" ] || die "cannot read recovery kit $RESTORE_KIT"
  has openssl || die "--restore needs openssl to open the recovery kit"
  pass="${KIT_PASSPHRASE:-}"
  if [ -z "$pass" ]; then
    tty_ok || die "set KIT_PASSPHRASE to the kit's passphrase (no terminal to ask on)"
    printf 'Recovery kit passphrase: ' >/dev/tty
    stty -echo </dev/tty 2>/dev/null || true
    IFS= read -r pass </dev/tty || true
    stty echo </dev/tty 2>/dev/null || true
    printf '\n' >/dev/tty
  fi
  opened=$(grep -v '^#' "$RESTORE_KIT" | tr -d ' \r\n' \
    | KIT_PASS="$pass" openssl enc -d -aes-256-cbc -pbkdf2 -iter 600000 -md sha256 -a -A -pass env:KIT_PASS 2>/dev/null) \
    || die "the passphrase does not open $RESTORE_KIT"
  pass=""
  [ "$(kit_value KIT_VERSION)" = 1 ] || die "the passphrase does not open $RESTORE_KIT, or it is not a recovery kit"
  RESTORE_KEY=$(kit_value SECRETS_KEY)
  [ -n "$RESTORE_KEY" ] || die "$RESTORE_KIT holds no SECRETS_KEY"
  if [ "$RELEASE_GIVEN" = 0 ] && [ -n "$(kit_value RELEASE)" ]; then RELEASE=$(kit_value RELEASE); fi
  if [ "$NAMESPACE_GIVEN" = 0 ] && [ -n "$(kit_value NAMESPACE)" ]; then NAMESPACE=$(kit_value NAMESPACE); fi
  dns_label --namespace "$NAMESPACE"
  dns_label --release "$RELEASE"
  SECRET_NAME="$RELEASE-secrets"
  PULL_SECRET_NAME="$RELEASE-registry"
  say "Opened the recovery kit made $(kit_value CREATED_AT) for $RELEASE in $NAMESPACE."
  opened=""
}
kit_value() { printf '%s\n' "$opened" | sed -n "s/^$1=//p" | head -n 1; }

# Before the first start, so the console opens the restored secrets with the
# key they were sealed with.
restore_secret() {
  if kube -n "$NAMESPACE" get secret "$SECRET_NAME" >/dev/null 2>&1; then
    current=$(kube -n "$NAMESPACE" get secret "$SECRET_NAME" -o jsonpath='{.data.SECRETS_KEY}' | base64 -d 2>/dev/null || true)
    [ "$current" = "$RESTORE_KEY" ] \
      || die "Secret $SECRET_NAME in $NAMESPACE holds another SECRETS_KEY; delete it (or the namespace) to restore"
    return 0
  fi
  PASSWORD=$(head -c 18 /dev/urandom | base64 | tr '+/' 'xy')
  (
    umask 077
    printf 'SECRETS_KEY=%s\nBOOTSTRAP_ADMIN_PASSWORD=%s\n' "$RESTORE_KEY" "$PASSWORD" >"$TMP/secret.env"
  )
  run kube -n "$NAMESPACE" create secret generic "$SECRET_NAME" --from-env-file="$TMP/secret.env" >/dev/null
  run kube -n "$NAMESPACE" label secret "$SECRET_NAME" "app.kubernetes.io/managed-by=$OWNER_LABEL" >/dev/null
  rm -f "$TMP/secret.env"
  say "Stored the kit's SECRETS_KEY in Secret $SECRET_NAME."
}

restore_failed() {
  kube -n "$NAMESPACE" delete pod "$RELEASE-restore" --ignore-not-found --wait=false >/dev/null 2>&1 || true
  kube -n "$NAMESPACE" scale deploy "$RELEASE" --replicas=1 >/dev/null 2>&1 || true
  die "$1 ($DISPLAY_NAME is back up on an empty database)"
}

# The console stops, a pod with its image and user mounts its volume, the
# copy replaces the database (and its WAL), and the console starts on it.
restore_database() {
  dep="deploy/$RELEASE"
  claim=$(kube -n "$NAMESPACE" get "$dep" \
    -o jsonpath='{.spec.template.spec.volumes[?(@.name=="data")].persistentVolumeClaim.claimName}' 2>/dev/null || true)
  [ -n "$claim" ] || die "$RELEASE keeps its data on no volume (persistence off), so there is nowhere to restore $RESTORE_FROM to"
  image=$(release_image)
  uid=$(kube -n "$NAMESPACE" get "$dep" -o jsonpath='{.spec.template.spec.securityContext.runAsUser}')
  gid=$(kube -n "$NAMESPACE" get "$dep" -o jsonpath='{.spec.template.spec.securityContext.fsGroup}')
  pull=""
  [ "$PULL_SECRET" = 0 ] || pull="  imagePullSecrets: [{ name: $PULL_SECRET_NAME }]"
  say "Restoring the database from $RESTORE_FROM ..."
  run kube -n "$NAMESPACE" scale "$dep" --replicas=0 >/dev/null
  kube -n "$NAMESPACE" wait --for=delete pod -l "app.kubernetes.io/instance=$RELEASE" --timeout="$TIMEOUT" >/dev/null 2>&1 || true
  cat >"$TMP/restore-pod.yaml" <<YAML
apiVersion: v1
kind: Pod
metadata:
  name: $RELEASE-restore
  labels: { app.kubernetes.io/managed-by: $OWNER_LABEL }
spec:
  restartPolicy: Never
$pull
  securityContext:
    runAsNonRoot: true
    runAsUser: ${uid:-10001}
    runAsGroup: ${gid:-10001}
    fsGroup: ${gid:-10001}
    seccompProfile: { type: RuntimeDefault }
  containers:
    - name: restore
      image: $image
      command: ["sleep", "3600"]
      securityContext: { allowPrivilegeEscalation: false, capabilities: { drop: ["ALL"] } }
      volumeMounts: [{ name: data, mountPath: /data }]
  volumes: [{ name: data, persistentVolumeClaim: { claimName: $claim } }]
YAML
  kube -n "$NAMESPACE" apply -f "$TMP/restore-pod.yaml" >/dev/null || restore_failed "could not start the restore pod"
  kube -n "$NAMESPACE" wait --for=condition=Ready "pod/$RELEASE-restore" --timeout="$TIMEOUT" >/dev/null \
    || restore_failed "the restore pod did not start"
  kube -n "$NAMESPACE" cp "$RESTORE_FROM" "$RELEASE-restore:/data/.$DB_FILE.restore" >/dev/null \
    || restore_failed "could not copy $RESTORE_FROM into the volume"
  # shellcheck disable=SC2016
  kube -n "$NAMESPACE" exec "$RELEASE-restore" -- sh -c \
    'cd /data && rm -f "$1-wal" "$1-shm" && mv ".$1.restore" "$1"' sh "$DB_FILE" \
    || restore_failed "could not put the copy in place"
  run kube -n "$NAMESPACE" delete pod "$RELEASE-restore" --wait=true >/dev/null
  run kube -n "$NAMESPACE" scale "$dep" --replicas=1 >/dev/null
  kube -n "$NAMESPACE" rollout status "$dep" --timeout="$TIMEOUT" >/dev/null
  rm -f "$TMP/restore-pod.yaml"
  say "Restored the database from $RESTORE_FROM."
}

do_install() {
  find_cluster
  if [ "$MODE" = install ] && [ "$KUBECONFIG_PATH" = "$K3S_KUBECONFIG" ]; then node_packages; fi
  install_helm
  if [ "$DRY_RUN" = 1 ] && ! helm_ok; then
    say "+ helm upgrade --install $RELEASE $CHART_REF --namespace $NAMESPACE ..."
    return 0
  fi

  existing=0
  hh status "$RELEASE" -n "$NAMESPACE" >/dev/null 2>&1 && existing=1
  if [ "$MODE" = update ]; then
    [ "$existing" = 1 ] || die "no release $RELEASE in namespace $NAMESPACE; install it with install.sh"
    [ "$UPGRADE_K3S" = 0 ] || upgrade_k3s
    if [ "$PREREQS" = 1 ]; then
      [ "$KUBECONFIG_PATH" = "$K3S_KUBECONFIG" ] || die "--prereqs installs packages on this host's k3s node, and the cluster in use is not it"
      NODE_PACKAGES=1
      node_packages
    fi
    before_chart=$(release_chart)
    before_image=$(release_image)
    # Keeps a port Kubernetes picked before the chart had a fixed default.
    if [ -z "$NODE_PORT" ] && [ -z "$HOST" ] \
      && [ "$(kube -n "$NAMESPACE" get svc "$RELEASE" -o jsonpath='{.spec.type}' 2>/dev/null || true)" = NodePort ] \
      && ! hh get values "$RELEASE" -n "$NAMESPACE" -o yaml 2>/dev/null | grep -q '^  nodePort:'; then
      NODE_PORT=$(kube -n "$NAMESPACE" get svc "$RELEASE" -o jsonpath='{.spec.ports[0].nodePort}' 2>/dev/null || true)
    fi
  fi
  # A Secret still there is a first install that didn't finish: run it again.
  if [ -n "$ENV_FILE" ] && [ "$existing" = 1 ] && ! kube -n "$NAMESPACE" get secret "$SEED_SECRET_NAME" >/dev/null 2>&1; then
    die "--env is for a first install, and $RELEASE is already installed in $NAMESPACE (move $ENV_FILE away to upgrade)"
  fi
  if [ -n "$RESTORE_KIT" ] && [ "$existing" = 1 ]; then
    die "--restore is for a fresh install, and $RELEASE is already installed in $NAMESPACE (install.sh --uninstall first)"
  fi
  check_webhooks
  ensure_namespace
  [ -z "$RESTORE_KEY" ] || restore_secret
  ensure_secret
  [ -z "$ENV_FILE" ] || write_seed_secret
  ensure_join_secret
  registry_auth
  [ -z "$HOST" ] || default_ingress_class
  [ -n "$HOST" ] || check_node_port "$existing"
  if [ "$existing" = 1 ]; then write_values 0; else write_values 1; fi

  set -- upgrade --install "$RELEASE" "$CHART_REF" --namespace "$NAMESPACE" \
    --wait --timeout "$TIMEOUT" -f "$TMP/values.yaml"
  case "$CHART_REF" in
    oci://*)
      if [ -n "$CHART_VERSION" ]; then
        set -- "$@" --version "$CHART_VERSION"
      else
        # Only prerelease builds are published until a release is tagged.
        set -- "$@" --devel
      fi
      ;;
  esac
  if [ "$existing" = 1 ]; then
    # --reset-then-reuse-values (Helm 3.14+) takes new chart defaults;
    # --reuse-values would pin the old ones.
    case "$(helm upgrade --help 2>/dev/null)" in
      *--reset-then-reuse-values*) set -- "$@" --reset-then-reuse-values ;;
      *) set -- "$@" --reuse-values ;;
    esac
  fi
  old_ifs="$IFS"
  IFS='
'
  set -f
  for v in $VALUES_FILES; do set -- "$@" -f "$v"; done
  set +f
  IFS="$old_ifs"

  if [ "$existing" = 1 ]; then say "Upgrading $RELEASE in $NAMESPACE ..."; else say "Installing $RELEASE into $NAMESPACE ..."; fi
  run hh "$@" >/dev/null
  [ "$DRY_RUN" = 0 ] || return 0
  kube -n "$NAMESPACE" rollout status "deploy/$RELEASE" --timeout="$TIMEOUT" >/dev/null
  [ -z "$RESTORE_FROM" ] || restore_database

  url=""
  host=$(kube -n "$NAMESPACE" get ingress "$RELEASE" -o jsonpath='{.spec.rules[0].host}' 2>/dev/null || true)
  origin=$(kube -n "$NAMESPACE" get deploy "$RELEASE" \
    -o jsonpath='{.spec.template.spec.containers[0].env[?(@.name=="PUBLIC_ORIGIN")].value}' 2>/dev/null || true)
  if [ -n "$origin" ]; then
    url="$origin/"
  elif [ -n "$host" ]; then
    url="http://$host/"
  else
    port=$(kube -n "$NAMESPACE" get svc "$RELEASE" -o jsonpath='{.spec.ports[0].nodePort}' 2>/dev/null || true)
    ip=$(node_ip)
    [ -z "$port" ] || [ -z "$ip" ] || url="http://$ip:$port/"
  fi

  if [ -n "$url" ] && has curl; then
    i=0
    until curl -fsS -o /dev/null --max-time 5 "${url}healthz" 2>/dev/null; do
      i=$((i + 1))
      if [ "$i" -ge 30 ]; then
        warn "$url does not answer from this host yet (DNS or ingress may still be settling)"
        break
      fi
      sleep 2
    done
  fi

  say ""
  if [ "$MODE" = update ]; then
    say "$DISPLAY_NAME is updated in namespace $NAMESPACE."
    say "Chart: $before_chart -> $(release_chart)"
    say "Image: $before_image -> $(release_image)"
  else
    say "$DISPLAY_NAME is ready in namespace $NAMESPACE."
  fi
  if [ "$ENABLE_DEPLOY" = 1 ]; then
    say "App deploys are on: Jobs in $NAMESPACE run as $RELEASE-installer, which is cluster-admin."
  fi
  if [ -n "$url" ]; then
    say "URL: $url"
  else
    say "Reach it with: $(kubectl_hint) -n $NAMESPACE port-forward svc/$RELEASE 8080:80"
  fi
  [ "$MODE" = install ] || return 0
  [ -z "$ENV_FILE" ] || remove_env_file
  if [ -n "$RESTORE_FROM" ]; then
    say ""
    say "Sign in with an account from the restored database."
    return 0
  fi
  if [ "$SEED_ADMIN_PASSWORD" = 1 ]; then
    say ""
    say "Sign in as admin with the ADMIN_PASSWORD from the env file."
    return 0
  fi
  if [ -n "$PASSWORD" ]; then
    say ""
    say "Sign in as admin with this password. It is shown once, and you will be asked to change it:"
    say "Password: $PASSWORD"
    say ""
    say "Until it is changed, it can be read again with:"
  else
    say "The first-sign-in password, if it has not been changed yet:"
  fi
  say "  $(kubectl_hint) -n $NAMESPACE get secret $SECRET_NAME -o jsonpath='{.data.BOOTSTRAP_ADMIN_PASSWORD}' | base64 -d"
}

if [ "$UNINSTALL" = 1 ]; then
  do_uninstall
else
  [ -z "$ENV_FILE" ] || read_env_file
  [ -z "$RESTORE_KIT" ] || open_kit
  do_install
fi
